### PR TITLE
Create and map CWE entities

### PR DESCRIPTION
**Pull request by fomentia**

### CODE REVIEW

**Comment by fomentia** [comment]
I want to reduce the number of times I loop through findings...

**Comment by aiwilliams** [comment]
> I want to reduce the number of times I loop through findings...

Do you mean I should wait to review?

**Comment by fomentia** [comment]
@aiwilliams Well, it's a draft PR, so yeah. 😆

**Comment by aiwilliams** [comment]
Oh, NICE! I didn't notice that. This is the first time I've seen one. Carry on.

**Pull request merged**
